### ISSUE TITLE
Getting Timeout error with any uploading files

### ISSUE THREAD

**Issue by ndbinh99** [balderdashy/skipper-s3#13]
Hi all,

This is error i got from console:
Unable to initiate stream upload [Error: connect ETIMEDOUT
I tried to use a small file with just 2kb, but the loading shows for some minutes and end with the error 500.
Sometimes it works, but almost it can't.
Sails: v0.10.5
Skipper-s3: 0.5.5

**Comment by sgress454** [comment]
@ndbinh99 There's really not enough information to go on here, and we haven't seen other similar reports, so it seems isolated to you.  Hopefully you were able to resolve!
