### ISSUE TITLE
Error: Unexpected response from AWS:{ Code: 'InvalidRequest' -> Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by dj-hedgehog** [balderdashy/skipper-s3#18]
I get this when trying to upload to S3:

```
Unable to initiate stream upload [Error: Unexpected response from AWS:{ Code: 'InvalidRequest',
  Message: 'The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.',
  RequestId: '8BA4CC4D85E17B20',
  HostId: 'TD8RZJF8Qdi0Gciy9LwatIUYH3CXVT3PFKqOlnn8tSz0z2l9GVfwbAMZjO3k/ShCowt/8ZnUf80=' }
```
**Is there a possibility to use the new V4 authorization scheme with Skipper S3** ?

This is my code doing the request
```
        file.upload({
            adapter: require('skipper-s3'),
            key: '----',
            secret: '----',
            bucket: 'my-bucket,
            dirname: year+'/' + '/' + month,
            saveAs: filename,
```

**Comment by jurajpetrik** [comment]
see here https://github.com/balderdashy/skipper-s3/issues/21

**Comment by sgress454** [comment]
Thanks @jurajpetrik 

@dj-hedgehog does the problem go away if you use a different region?

**Comment by dj-hedgehog** [comment]
@sgress454 yeah, I switched from Frankfurt to North America. Are there any plans to support the V4 authorization scheme anytime?

**Comment by timohofmeijer** [comment]
:+1:  V4

**Comment by newenegue** [comment]
+1 v4!

**Comment by newenegue** [comment]
See these issues with knox that are related:

https://github.com/Automattic/knox/pull/273

https://github.com/Automattic/knox/issues/254

**Comment by pendar747** [comment]
would be cool if it gets implemented

**Comment by sgress454** [comment]
Closing for now--if v4 isn't supported in Knox, we can't support it in Skipper-S3.  If it gets merged into Knox, we'll try to pull it through!

**Comment by eltonk** [comment]
+1
