### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by zfrenchee** [balderdashy/skipper-s3#25]
I'm trying to use dropzone on the frontend to serialize images on s3. My FileController code looks roughly like: 

		req.file('groupImage').upload({
			adapter: require('skipper-s3'),
			key: 'key',
			secret: 'secret',
			bucket: 'group.images'
		}, function whenDone(err, uploadedFiles) {
			if (err) { console.log(err); return res.serverError(err);  }
			else { 
				console.log(uploadedFiles);
				return res.json({ files: uploadedFiles, textParams: req.params.all() }); }
		});
	},

The second console log prints an empty array, and err is null, meaning that it seems nothing has happened. The bucket is empty after the "upload". I tried a couple things: 
- I wanted to get an idea of what req.file('groupImage') was, so I console logged it right before 'upload' and it always crashed the app, the second field of the output was "isNoop: true, " which sounds foreboding. 
- I thought it might be that s3 now wants IAM credentials rather than traditional keys/secrets, but changing that had no effect. 
- I tried to clone and do the npm test, which failed 

		  1) "before all" hook

		  0 passing (82ms)
		  1 failing

		  1)  "before all" hook:
		     Uncaught Error: listen EADDRINUSE
		      at errnoException (net.js:905:11)
		      at Server._listen2 (net.js:1043:14)
		      at listen (net.js:1065:10)
		      at Server.listen (net.js:1139:5)
		      at Function.app.listen (/Users/Alex/Documents/skipper-s3/node_modules/skipper-adapter-tests/node_modules/connect/lib/proto.js:232:24)
		      at Context.Helpers.setup (/Users/Alex/Documents/skipper-s3/node_modules/skipper-adapter-tests/lib/helpers.js:71:20)
		      at Hook.Runnable.run (/Users/Alex/Documents/skipper-s3/node_modules/skipper-adapter-tests/node_modules/mocha/lib/runnable.js:196:15)
		      at next (/Users/Alex/Documents/skipper-s3/node_modules/skipper-adapter-tests/node_modules/mocha/lib/runner.js:259:10)
		      at Object._onImmediate (/Users/Alex/Documents/skipper-s3/node_modules/skipper-adapter-tests/node_modules/mocha/lib/runner.js:276:5)
		      at processImmediate [as _immediateCallback] (timers.js:354:15)

Given the issues, this repository feels abandoned. Is there a machinepack on the way or something? @sgress454

**Comment by sgress454** [comment]
`EADDRINUSE` indicates that you have a Sails app running on 1337.  Try killing all other node processes before running the test.  You'll also need to set some environment vars for the tests to work; check out the [contributing section](https://github.com/balderdashy/skipper-s3/blob/master/README.md#contribute) for details.

**Comment by sgress454** [comment]
As far as the silent error, check out https://github.com/balderdashy/skipper-s3/issues/21--perhaps it's your bucket location that's the issue?

**Comment by zfrenchee** [comment]
Hi Scott, I saw that second part, and it isn't in Frankfurt, it's in US Standard East. I'll try the tests. Thanks!

**Comment by zfrenchee** [comment]
Nearly all the tests worked, which means it must be some way that I'm sending the files over. Is there any way for me to see the req.file('groupImage')?

**Comment by sgress454** [comment]
That's a stream of streams; you can pipe it to your own handler, and once a new file stream is received (if ever) pipe *that* to something that logs the bytes.  But, that's what the receivers do anyway; you might as well just try it with `skipper-disk` and see if it writes the file to disk.  Have you already ruled out issues on the client side?  That is, are you sure the file is sending at all?  If you're using Chrome, you can use the dev tools to examine the outgoing request to see if the file is in there.  You can also try using a tool like Postman to hit your Sails route directly with a file and see if that works, which would also point to a client-side issue.

**Comment by zfrenchee** [comment]
Alright, thanks! I've tested it with Postman, and the backend definitely works, so something is broken on my frontend.

**Comment by zfrenchee** [comment]
Works now. That was really strange. I didn't change anything and it just started working. How peculiar.

**Comment by zfrenchee** [comment]
Just one question left: Now that I can upload files to S3, do you have a system to recommend that allows me to manipulate what's in an s3 bucket from a sails app (e.g. deleting files)?
