### ISSUE TITLE
File uploaded but permission is wrong. Can't view it in browser.

### ISSUE THREAD

**Issue by anandmahajan** [balderdashy/skipper-s3#26]
How to set permission during upload ?

**Comment by zfrenchee** [comment]
Read #6 and then [this stackoverflow post](http://stackoverflow.com/questions/25206528/how-to-add-acl-and-content-type-parameters-when-using-skipper-s3)

**Comment by NoRKin** [comment]
Very short version:

Just add `headers: {
                'x-amz-acl': 'public-read'
 }`

**Comment by sgress454** [comment]
@zfrenchee @NoRKin Thanks guys!
