### ISSUE TITLE
NPM latest version is 0.5.5

### ISSUE THREAD

**Issue by GeoffreyPlitt** [balderdashy/skipper-s3#34]
https://www.npmjs.com/package/skipper-s3

When will 0.5.6 or 0.5.7 be published?

**Comment by GeoffreyPlitt** [comment]
HELLO

**Comment by mikermcneil** [comment]
0.5.8 was just published

**Comment by mikermcneil** [comment]
@GeoffreyPlitt oops my bad, got confused with Skipper (versions are almost exactly the same)

**Comment by mikermcneil** [comment]
@GeoffreyPlitt actually... I'm a little confused.  There is no `0.5.5` or `0.5.6` for the skipper-s3 package-- sounds like we both made the same mistake :)

**Comment by sgress454** [comment]
Many confusions, because the NPM version was 0.5.5 but the version bump never got pushed to Github, so that the package.json in the repo was 0.5.4.  Annnnyways we just published 0.5.6, and to all a good night!

**Comment by GeoffreyPlitt** [comment]
https://www.npmjs.com/package/skipper-s3 0.5.6 looks right, thanks!
