### ISSUE TITLE
Is there a way to upload files to a specific folder within an S3 bucket?

### ISSUE THREAD

**Issue by tayste5000** [balderdashy/skipper-s3#44]
As of now I see no way to upload a file to a specific folder in an S3 bucket. I would normally do this by prepending the folder name to the filename. I cannot find any option to control the filename in this package...am I missing something?

**Comment by AlexanderKozhevin** [comment]
+1

**Comment by mattcodez** [comment]
I'm using sub folders via the `saveAs` option:
`saveAs: getS3Filename`
...
```
function getS3Filename(fs, cb){
      let subFolder = process.env.NODE_ENV !== 'production' ? 'devel/' : '';
      let finalS3Path =
        `${S3Folder}${subFolder}${uuid.v4()}${path.extname(fs.filename)}`;
      cb(null, finalS3Path);
    }
```

**Comment by tayste5000** [comment]
Thanks, I managed to figure this out after a good bit of research. It wouldn't hurt to make this more clear in the docs.

**Comment by irlnathan** [comment]
Howdy @tayste5000,

If you have the time would you mind taking a crack at updating the docs?

Thanks!

Best, Irl

**Comment by agarwalswapnil** [comment]
Guys,
Sorry for commenting on a closed issue.
Is this functionality present now ? I need it for my project too.

**Comment by sgress454** [comment]
@agarwalswapnil See the [comment above](https://github.com/balderdashy/skipper-s3/issues/44#issuecomment-190335641) about how to use the [`saveAs` option of `.upload()`](https://github.com/balderdashy/skipper#options) to specify a subfolder on S3.
