### ISSUE TITLE
Unable to initiate stream upload [Invalid upload ID

### ISSUE THREAD

**Issue by charlitos85** [balderdashy/skipper-s3#9]
I try to upload somothing to s3. 
Sometimes i receive this message "Unable to initiate stream upload [Invalid upload ID".
But Sometimes upload correct.

**Comment by sgress454** [comment]
So it seems like the issue is that certain regions use certain signature schemes that the underlying [Knox](https://github.com/automattic/knox) module doesn't support.  We'll try to keep up-to-date with develops here, but in the meantime, the solution is to change to a supported region.
